config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  
  resources :posts do 
    resources :comments 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  #has_many :comments
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy 
    validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    #http_basic_authenticate_with name: "admin", password: "123"

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "123", except: [:index, :show]
    #обработка главной странички
    def index
        @post = Post.all
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
        #для проверки данных
        #render plain: params[:post].inspect
        @post = Post.new(post_params)

        if @post.save
            redirect_to @post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to @post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, status: :see_other
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="cheatsheet.css" rel="stylesheet">
  </head>
  
  <body>
  
  <header class="bd-header bg-dark py-3 d-flex align-items-stretch border-bottom border-dark">

    <div class="container-fluid d-flex align-items-center">
    <%= image_tag "pngwing.jpg", size: "30x30", :alt => "rss feed" %>
      <h1 class="d-flex align-items-center fs-4 text-white mb-0">
  
           Filmopoisk
      </h1>
      <span class="ms-auto link-light" ><%= link_to "Main", home_path, :style=>'color: white;'%></span>
      <span class="ms-auto link-light" ><%= link_to "Addition", new_post_path, :style=>'color: white;' %></span>
      <span class="ms-auto link-light"><%= link_to "About us", about_path, :style=>'color: white;' %></span>
    </div>
  </header>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4>Фильмопоиск. Онлайн кинотеатр.</h4>
<p> Фильмопоиск — это крупнейший сервис о кино в рунете. 
На нем вы сможете узнать рейтинги популярных фильмов и
 их описание, оставить отзыв, написать рецензии и дополнить описание фильмов.</p>

app/views/posts/edit.html.erb
<h2>Редактирование</h2>
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %> </div>
        <% end %>
    <% end %>
    <p>
        Название<br>
        <!-- дляназвания текста -->
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        Описание<br>
        <!--для большого количества текста -->
        <%= f.text_area(:body, {:class => 'form-control'})  %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-success'})  %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Описание фильмов</h1>
<% @post.each do |post| %>
    <div class="alert alert-light">
        <h3><%= post.title %></h3>
        <h5><%= post.body %></h5>
        <%= link_to "Читать далее", post_path(post), :class => 'btn btn-outlina-primary' %>
    </div>
<%end%>

app/views/posts/new.html.erb
<h2>Добавить новый фильм</h2>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %> </div>
        <% end %>
    <% end %>
    <p>
        Название<br>
        <!-- дляназвания текста -->
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        Описание<br>
        <!--для большого количества текста -->
        <%= f.text_area(:body, {:class => 'form-control'})  %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-success'})  %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить", post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Хотите удалить статью?"}, :class => 'btn btn-danger' %>
<hr>
<h2>Все комментарии</h2>
<% @post.comments.each do |comment| %>
    <div class="alert alert-light">
        <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
    </div>
<%end%>

<hr>
<h2>Оставить комментарий</h2>
<%= form_for [@post, @post.comments.build] do |f| %>
    <p>
        Пользователь<br>
        <!-- дляназвания текста -->
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        Текст коментария<br>
        <!--для большого количества текста -->
        <%= f.text_area(:body, {:class => 'form-control'})  %>
    </p>

    <p>
        <%= f.submit("Добавить",{:class => 'btn btn-warning'})  %>
    </p>
<% end %>